id: PF5724065
initial_creation_type: input
source_metadata:
  title: Alak Zenkar Rinpoche
  language: en
  description: 'Texts by and about the great scholar Alak Zenkar Rinpoche Thupten
    Nyima (a lags gzan dkar thub bstan nyi ma, b.1943):'
  volume:
    026fbeb7049446ea8fe0f84c867acfa2:
      title: Biography of Jamgön Kongtrul Lodrö Thaye
      parent: Biography
    f67a107779234ca9aa83fc1fc61e1cde:
      title: Biography of Jamyang Khyentse Wangpo
      parent: Biography
    0ca499260815432fb21cc0005ca86dbd:
      title: Biography of Patrul Rinpoche
      parent: Biography
    dc5ff05e93244f01bcaf0344f28310d2:
      title: Biography of Shechen Gyaltsab Gyurme Pema Namgyal
      parent: Biography
    d37955ebb10d451090726b5664358df5:
      title: Brief Biography of Drakkar Lobzang Palden
      parent: Biography
    e97e38a4633f4909aa610cc05088f662:
      title: Brief Biography of Kharlek Tulku Pema Kunzang Rangdrol
      parent: Biography
    696ec4816eda407b9068188d8e29622e:
      title: Brief Biography of Tāranātha
      parent: Biography
    3b387d98f3af4077a10ff70b1d016f28:
      title: A Brief Presentation of the Nine Vehicles
      parent: Buddhist Philosophy
    20312225c6c84cca9200afb9e7de8e8b:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Long Life Prayers
    6b10f7ddc6e04289a9de475780d21e99:
      title: Long Life Prayer for Patrick Gaffney (Yeshé Wangyal)
      parent: Long Life Prayers
    25f7f097d00e433b86ff084486b308dd:
      title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of
        Do Khyentsé Yeshé Dorjé
      parent: Long Life Prayers
    2e197cfe248f4bcb89652e4386cd93b1:
      title: 'Bodhicaryāvatāra: Teachings and Overview'
      parent: Oral Teachings
    aeaa343e5e7946d4869509038d8b6e86:
      title: Light from the Wisdom Sun
      parent: Prayers and Practices
    b11a543d336a4b2ca4c22c640f0cb7b4:
      title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
      parent: Swift Rebirth Prayers
    86cb837ccfb346c0996e89d47d99789a:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-02-28T22:37:59.742931'
last_modified_at: '2022-02-28T22:37:59.742938'
